### ISSUE TITLE
Activity 1: Your First Caption

### ISSUE THREAD

**Issue by vvaths** [InfoMSandbox/real-deal-ccc#3]
Using the API, I have just created a file with a random octocat for you to caption. In this activity, we will learn how to make changes to files in our GitHub repository.

- [ ] @anbu2CCC
- [ ] @arunmurukesh
- [ ] @bthammi
- [ ] @dr29bart
- [ ] @mokef-hub
- [ ] @psrbala
- [ ] @scottsabre
- [ ] @sweetsmile2122
- [ ] @vvaths
- [ ] @ythaku
- [ ] @omar-rahmoun
- [ ] @vchebota-ccc
- [ ] @vyas000

**Comment by vchebota-ccc** [comment]
test
